[package]
name = "crt-terminal"
version = "0.1.39"
description = "CRT Terminal desktop app"
authors = ["CRT Terminal"]
edition = "2021"

[lib]
name = "crt_terminal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde_json = "1"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
